### ISSUE TITLE
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by martylamb** [h3rald/hastyscribe#36]
Hi,

I'm getting the above error on any source file when running v1.1.2 Linux x86 binary as downloaded from the website.

This is running on Fedora 22, specifically:

```
Linux fnog 4.1.5-100.fc21.x86_64 #1 SMP Tue Aug 11 00:24:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Note that this was working absolutely perfectly for some time until Fedora picked up an update (or updates) recently.  Unfortunately I don't know which update was the first to break it.

Happy to help or test in any way I can but have no knowledge of Nim.

\- Marty

**Comment by h3rald** [comment]
Hi! Thanks for reporting this.

Actually I tried compiling HastyScribe on a Linux machine (running Ubuntu) and I get exactly the same error.

I'll investigate and keep you posted...

**Comment by martylamb** [comment]
Just confirmed this fix works for me.  Thanks!

**Comment by h3rald** [comment]
Glad to hear that! :)

On Tue 8 Sep 2015 at 18:06 martylamb <notifications@github.com> wrote:

> Just confirmed this fix works for me. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/h3rald/hastyscribe/issues/36#issuecomment-138613471>.
>
-- 
-- Fabio Cevasco
H3RALD.com
