### ISSUE TITLE
Accentued caracters

### ISSUE THREAD

**Issue by zemadmat** [h3rald/hastyscribe#50]
Hi,
How can i have a valid output with accentued caracters ?
For the moment when i convert a such caracter i have a question mark.

intégration -> int�gration
Cheers

**Comment by h3rald** [comment]
Hi, 

I did some simple tests and in my case accented characters like àèìòù seem to work fine, when I just input them with the keyboard.

For sure at worst you could encode them as HTML entitites, e.g. &agrave; &egrave; &igrave; etc.: (see [this](http://www.w3schools.com/charsets/ref_html_entities_a.asp) for more info)... but could you please attach the markdown file you are trying to convert, so I can test it and see?

**Comment by zemadmat** [comment]
Hi please find attached the incriminated file :)
Cheers 

    Le Mardi 10 janvier 2017 11h34, Fabio Cevasco <notifications@github.com> a écrit :
 
 

 Hi,I did some simple tests and in my case accented characters like àèìòù seem to work fine, when I just input them with the keyboard.For sure at worst you could encode them as HTML entitites, e.g. à è ì etc.: (see this for more info)... but could you please attach the markdown file you are trying to convert, so I can test it and see?—

**Comment by h3rald** [comment]
Mmmm can't find any file... could you attach it to the github issue or send it by email to h3rald@h3rald.com.

Thanks!

**Comment by h3rald** [comment]
Cannot reproduce; closing this issue.
