### ISSUE TITLE
h3rald.com Mac OS X pre-built binary link is dead

### ISSUE THREAD

**Issue by sbwoodside** [h3rald/hastyscribe#52]
[Downloading Pre-built Binaries](https://h3rald.com/hastyscribe/HastyScribe_UserGuide.htm#Downloading-Pre-built-Binaries) gives a [Mac OS X link](https://github.com/h3rald/hastyscribe/releases/download/v1.6.0/hastyscribe_v1.6.0_macos_x64.zip) which takes me to a GitHub 404 page.

**Comment by dom96** [comment]
Looks like a small typo https://github.com/h3rald/hastyscribe/releases/download/v1.6.0/hastyscribe_v1.6.0_macosx_x64.zip

**Comment by h3rald** [comment]
Indeed... well spotted!

I’ll fix it right away! Thanks!
