### ISSUE TITLE
Linux binary doesn't run on Kubuntu 20.04 LTS

### ISSUE THREAD

**Issue by hohlerde** [h3rald/hastyscribe#73]
Downloaded the latest linux binary from the releases page.

Extracted and tried to run it on Kubuntu 20.04 LTS. I get the following error:

```
bash: ./hastyscribe: No such file or directory
```

`ldd hastyscribe` gives:

```
./hastyscribe: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so: invalid ELF header
```

`file hastyscribe` gives:

```
hastyscribe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
```

So, I guess I need to install musl in order to use hastyscribe binary?

**Comment by h3rald** [comment]
Yeah, annoying. I can reproduce it on my linux machine... The problem is that I run my release scripts from my mac and I cross-compile the executables for linux and windows. I'll try to see what the problem is. In theory it should run fine and it should be compiled statically.
