### ISSUE TITLE
Non ascii characters are not rendered properly with utf8 markdown file

### ISSUE THREAD

**Issue by phb95** [h3rald/hastyscribe#84]
A way to reproduce #50 is with an utf8 encoded markdown file.
After converting it to latin1 the output is correct.

**Comment by h3rald** [comment]
I really cannot reproduce it. I created a file containing some Unicode characters, and it's UTF-8 encoded as you can see from VS Code status bar:

<img width="979" alt="Screenshot 2021-07-03 at 14 34 31" src="https://user-images.githubusercontent.com/1169/124354368-f2baa000-dc0b-11eb-9b6a-82d7e88b9cb2.png">

After running HastyScribe, the resulting HTML looks fine:

<img width="612" alt="Screenshot 2021-07-03 at 14 35 17" src="https://user-images.githubusercontent.com/1169/124354406-21387b00-dc0c-11eb-91fb-8c5bb8d18760.png">

Ideas?

**Comment by phb95** [comment]
I checked more thoroughly and I'm afraid the issue is on my side.
The same utf8 file is ok when read from disk and ko when served by a (poorly configured) internal web server.
Sorry for the wasted time.
