### ISSUE TITLE
No HTML <title> tag if not using Pandoc headers

### ISSUE THREAD

**Issue by celtic-coder** [h3rald/hastyscribe#86]
Hi Fabio (@h3rald,)

When I don't use the Pandoc-style metadata headers (#6), the <title> tag is missing from the output HTML file. 

For example, the following Markdown uses the headers:

![pandoc-header-md](https://user-images.githubusercontent.com/11787866/140587109-1280b013-c9bb-45fa-a8d5-b37bf3d61e0a.png)

and it generates the HTML with the <title> tag:

![pandoc-header-html](https://user-images.githubusercontent.com/11787866/140587352-d4b8b2ea-f219-4606-9a38-9b35d324a12f.png)

However, if I use my own H1 header tag and do not use the Pandoc-style headers as given below:

![no-pandoc-header-md](https://user-images.githubusercontent.com/11787866/140587566-c89477fc-286b-4abe-bd56-2499028ddb73.png)

then the HTML is missing the <title> tag as seen here:

![no-pandoc-header-htm](https://user-images.githubusercontent.com/11787866/140587754-c76db2d3-5095-4d1e-8ce7-9a2ecc82e40a.png)

It looks like the issue is in lines 359 to 367 in the [hastyscribe.min](https://github.com/h3rald/hastyscribe/blob/3162b1afbab2f52a9ae75c884a23ca601bf5f8c1/src/hastyscribe.nim#L359-L367) file. The value of "title_tag" is being written in line [396](https://github.com/h3rald/hastyscribe/blob/3162b1afbab2f52a9ae75c884a23ca601bf5f8c1/src/hastyscribe.nim#L394-L400), but it is blank. **If the Pandoc-style headers are not being used, should the title tag not be populated from the H1 tag created by the user?**

By the way, is there a reason why the Table of Contents is in a different position depending on whether the Pandoc-style headers are used? For example, if they **are** used, they appear *below* the Pandoc H1 header:

![pandoc-header-toc](https://user-images.githubusercontent.com/11787866/140589214-27d59a79-5ab1-40b9-a710-cb2bfc610708.png)

If they are **not** being used, then they appear *above* the H1 header:

![no-pandoc-header-toc](https://user-images.githubusercontent.com/11787866/140589428-feeb9adc-b007-4d09-aa97-759ebc10b86a.png)

This is just a minor detail, a point of curiosity! :)

It would be helpful, however, if you could address the <title> tag issue.

Kind Regards,
Liam

**Comment by h3rald** [comment]
Well, I did investigate this a bit, and the short answer is that typically HastyScribe is meant to be used with Pandoc headers, if you are creating a "proper" document with a title and a TOC, otherwise, there is no real way to set a proper title. Yes, you can get the style of the document title if you use a h1 tag, but that will not actually be the document title, it will be part of the document...

If you specify a title using the Pandoc header, HastyScribe generates the initial H1 for you *above* the TOC, otherwise if you add it it will be placed below, and it will mess up the TOC. 

I don't think I am going to support alternatives which would involve parsing the first H1 tag... it's kinda messy, it's better to use the Pandoc headers.

**Comment by celtic-coder** [comment]
Hi Fabio (@h3rald),

Yes, this is perfectly understandable! 

I am using the [Leo outlining editor](https://leoeditor.com/preface.html) to create my Markdown documents. It auto generates the #'s required for each level of the outline.

This means that I can move around the different text blocks in the document without ever having to think about the amount of #'s required for the associated heading. However, the Markdown exporter always starts at H1, which contradicts using the Pandoc-style headers.

Since I require a proper **\<title\>** tag in the generated HTML, my workaround is to make a slight change in the Python exporter code to increment the level of the heading. Now, I have the best of both worlds!

Thanks again for your work on *HastyScribe* - much appreciated! 😄 

Kind Regards,
Liam
