### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by h3rald** [h3rald/hastyscribe#9]
Add support for syntax highlighting in code snippets

**Comment by andreaferretti** [comment]
Is there any info on how to use syntax highlighting, or which languages are supported? I couldn't find anything in the guide.

It seems that `~~~js` is supported (but not highlighted), while `~~~nim` is not

**Comment by h3rald** [comment]
Hi!

Well, HastyScribe *did* support syntax highlighting very briefly before it's 1.0 release, hence you can't find anything in the guide now.

The main problem is that syntax highlighting typically must rely on JavaScript, and I thought about it for a while but in the end I decided to keep HastyScribe JavaScript-free to keep it simple and (slightly more) lightweight (except that now it embeds like four font faces in all documents by default, but that's another story).

Now, actually in some cases syntax highlighting could be useful, so maybe what I could do is provide an extra command like option like --js:myfile.js to enable embedding of a custom JavaScript file. In this case you could just use highlight.js or whatever library or bundle you need and do pretty much whatever you want.

What do you think? Would that be a good compromise?

**Comment by andreaferretti** [comment]
Thank you, that would be a great option!

In any case, syntax highlighting need not rely on javascript: there are quite a few libraries to do syntax highlighting in other languages, that could be used to do all the work statically, if you prefer so. Unfortunately, I couldn't find many of them with C bindings (the most common, pygments, is in python).

**Comment by h3rald** [comment]
Yes that's the problem: there are a lot of highlighting libraries in languages like Ruby, Python and Javascript, but not many in C. I'll investigate a little bit, because I'd like to statically link a C library instead of relying on Javascript...

There's actually a Nim library that supports only a few languages, but it may be worth looking into:

http://nim-lang.org/docs/highlite.html

I am going to re-open this issue for now, I'll try to look into it soon (not this weekend because there's Lucca Comics ;), but the weekend after this one maybe).

**Comment by andreaferretti** [comment]
Have fun in Lucca: it is my home town! :-)
