### ISSUE TITLE
`create_otional_css` logic bug?

### ISSUE THREAD

**Issue by ZoomRmc** [h3rald/hastyscribe#92]
https://github.com/h3rald/hastyscribe/blob/36ccb49f685c6d030d158696d46c204006d326d0/src/hastyscribe.nim#L387-L402

I'm not yet sure what this code does, but I'm pretty sure it doesn't do what the comments imply it does.

1. `op` is written to max once per iteration
2. `matches` seq is initialized anew once per iteration
3. Then `op` is compared multiple times (lines 393, 395, 397) with different strings so only one comparison can ever evaluate to `true`. This construction is equivalent to 
  ```nim
  if (op == "$=" and href.endsWith(value)) or 
     (op == "*=" and href.contains(value)) or
     (op == "^=" and href.startsWith(value)):
     matches.add key 
  ```
4. This means `matches` never has more than one element but it's treated as if it can. Perhaps it needs to move up a scope?

I've simplified this code in my branch retaining the current behavior but I'm not sure it does what it's supposed to, so I'd be glad if you could run me through it.

**Comment by h3rald** [comment]
You may be right you know... I kinda rushed this part a little bit, originally I didn't check for the "op" ($=, ^=, *=) and did three checks "prioritizing" the last one. Introducing a check for the "op" made the whole "prioritization" unnecessary, so yes, if you modified this part in your branch feel free to send a PR!

**Comment by ZoomRmc** [comment]
I've just simplified the code but the bug is still there.
If you could hint me to what this code is intended to do I can fix it.
Which rule matches for each href do we want to save and which to discard?

UPD: I've updated the function in #90 ([9a523af](https://github.com/h3rald/hastyscribe/pull/90/commits/9a523af528d5f43789fde0d9e64b7835c615d66e)) but didn't change the logic yet.

**Comment by h3rald** [comment]
Alright, so basically here's how it is supposed to work. [hastystyles.links.css](https://github.com/h3rald/hastyscribe/blob/master/src/hastyscribepkg/data/hastystyles.links.css) contains some CSS rules to add an icon to links depending on their target.

There are essentially three types of rules:

* href **ends with** something , e.g. `a[href$='.zip']:before`, typically for extensions
* href **contains** something, e.g. `a[href*='github.com']:before`, typically to match specific domains
* href **starts with** something, e.g. `a[href^='http']:before`, typically for protocols

Now, these three types of rules are in order of precedence, for example, if you check [here](https://h3rald.com/hastyscribe/HastyScribe_UserGuide.htm#Downloading-Pre-built-Binaries):

![image](https://github.com/h3rald/hastyscribe/assets/1169/59003c86-2dda-4783-a896-e0dbc0b58be9)

...the zip icon is displayed, so given this link that would potentially match all three rules:

https://github.com/h3rald/hastyscribe/releases/download/v2.0.0/hastyscribe_v2.0.0_macosx_x64.zip

...only the first one is considered.

Then... normal github links that don't link ZIP or PDF files like this one:

https://github.com/h3rald/hastyscribe

...would match the "contains" rule, and then if there's no matching contains rule (e.g. http://nim-lang.org/) then the "starts with" rule is used (starts with http) to show a generic globe icons for HTTP links.

Does it make more sense now?
